- 👋 Hi, I’m @Hafeesh
- 👀 I’m interested in machine learning enginneer role
- 🌱 I’m currently learning at ANNA UNIVERSITY CHENNAI
- 💞️ I’m looking to collaborate on AIcompanies
- 📫 How to reach me akhafeez07@gmail.com

<!---
Hafeesh/Hafeesh is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
